### ISSUE TITLE
Aislar resultado del requests(discord.py)

### ISSUE THREAD

**Issue by Pachec00** [andalugeeks/andaluh-discord#1]
{'rules': {'vvf': 'h', 'vaf': 'z', 'escapeLinks': 'True'}, 'andaluh': 'ola', 'spanish': 'hola'}
Aislar el resultado para que por ejemplo en ese caso solo quede "ola".

**Comment by fontanon** [comment]
It's easy @Pachec00. The response is nothing but a python dict object. Have a look on how to access the "andaluh" element:

```python
>>> response = {'rules': {'vvf': 'h', 'vaf': 'z', 'escapeLinks': 'True'}, 'andaluh': 'ola', 'spanish': 'hola'}
>>> print response['andaluh']
<<< ola
```
